import type { ConfigDefinition } from "./types.ts";

export const DEFAULT_CONFIG_DEFINITIONS = [
  {
    key: "APP_ENV",
    description: "Application environment name.",
    kind: "string",
    defaultValue: "development",
    meta: { hotReload: false, sensitive: false, restartRequired: true },
  },
  {
    key: "APP_PORT",
    description: "HTTP port for the backend API.",
    kind: "number",
    defaultValue: 3000,
    meta: { hotReload: false, sensitive: false, restartRequired: true },
  },
  {
    key: "LOG_LEVEL",
    description: "Structured logging level.",
    kind: "string",
    defaultValue: "info",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_STORE_PATH",
    description: "Persistent state store file path for baseline runtime repositories.",
    kind: "string",
    defaultValue: "out/v3/state/menu-fit-state.json",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_STORE_DRIVER",
    description: "Persistent state store runtime driver (file, sqlite, or postgres).",
    kind: "string",
    defaultValue: "file",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_STORE_SQLITE_PATH",
    description: "SQLite state store path when STATE_STORE_DRIVER=sqlite.",
    kind: "string",
    defaultValue: "out/v3/state/menu-fit-state.sqlite",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_STORE_POSTGRES_URL",
    description: "Postgres connection string when STATE_STORE_DRIVER=postgres.",
    kind: "string",
    defaultValue: "",
    meta: { hotReload: false, sensitive: true, restartRequired: false },
  },
  {
    key: "STATE_STORE_POSTGRES_LOCK_PATH",
    description: "Lease lock file path used by postgres runtime driver.",
    kind: "string",
    defaultValue: "out/v3/state/menu-fit-state.postgres.lock",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_BACKEND",
    description: "Distributed lock backend (file or redis).",
    kind: "string",
    defaultValue: "file",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_KEY",
    description: "Logical lock key for external lock backends.",
    kind: "string",
    defaultValue: "persistent-state-store",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_LEASE_TTL_MS",
    description: "Lease TTL in milliseconds for distributed lock coordination.",
    kind: "number",
    defaultValue: 30000,
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_RENEW_INTERVAL_MS",
    description: "Lease renewal interval in milliseconds for external lock backends.",
    kind: "number",
    defaultValue: 10000,
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_MAX_WAIT_MS",
    description: "Maximum wait time in milliseconds to acquire distributed lock.",
    kind: "number",
    defaultValue: 5000,
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_RETRY_DELAY_MS",
    description: "Retry delay in milliseconds between distributed lock acquire attempts.",
    kind: "number",
    defaultValue: 50,
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_FAIL_OPEN",
    description: "When true, proceed without external lock on backend failure.",
    kind: "boolean",
    defaultValue: true,
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "STATE_LOCK_REDIS_URL",
    description: "Redis connection URL when STATE_LOCK_BACKEND=redis.",
    kind: "string",
    defaultValue: "",
    meta: { hotReload: false, sensitive: true, restartRequired: false },
  },
  {
    key: "STATE_LOCK_REDIS_KEY_PREFIX",
    description: "Redis key prefix for external lock records.",
    kind: "string",
    defaultValue: "menufit:locks",
    meta: { hotReload: false, sensitive: false, restartRequired: false },
  },
  {
    key: "PG_LOGIN_URL",
    description: "Project Gezond login endpoint.",
    kind: "url",
    defaultValue: "https://backend.projectgezond.nl/api/login",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "PG_WEEK_URL_TEMPLATE",
    description: "Project Gezond week endpoint template.",
    kind: "url",
    defaultValue: "https://backend.projectgezond.nl/api/v3/week-menus/{week}",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "PG_DAY_URL_TEMPLATE",
    description: "Project Gezond day endpoint template.",
    kind: "url",
    defaultValue: "https://backend.projectgezond.nl/api/v3/daymenus/{dayId}",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "PG_RECIPE_URL_TEMPLATE",
    description: "Project Gezond recipe endpoint template.",
    kind: "url",
    defaultValue: "https://backend.projectgezond.nl/api/v3/recipes/{recipeId}",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "PG_SHOPPINGLIST_URL_TEMPLATE",
    description: "Project Gezond shopping list endpoint template.",
    kind: "url",
    defaultValue: "https://backend.projectgezond.nl/api/v3/week-menus/{week}",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "PG_EXTRA_HEADERS_JSON",
    description: "Extra headers for Project Gezond API calls.",
    kind: "json",
    defaultValue: { "X-Requested-With": "XMLHttpRequest" },
    meta: { hotReload: true, sensitive: true, restartRequired: false },
  },
  {
    key: "LLM_PROVIDER",
    description: "Configured LLM provider profile.",
    kind: "string",
    defaultValue: "openai",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "LLM_BASE_URL",
    description: "Base URL for the active LLM provider.",
    kind: "url",
    defaultValue: "https://api.openai.com/v1",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "LLM_MODEL",
    description: "Model identifier used for LLM completion requests.",
    kind: "string",
    defaultValue: "gpt-4o-mini",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "LLM_AZURE_DEPLOYMENT",
    description: "Azure OpenAI deployment name mapped to the configured model.",
    kind: "string",
    defaultValue: "",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "LLM_API_KEY",
    description: "Secret key for the active LLM provider.",
    kind: "string",
    defaultValue: "",
    meta: { hotReload: true, sensitive: true, restartRequired: false },
  },
  {
    key: "LLM_API_VERSION",
    description: "Provider API version for compatibility checks.",
    kind: "string",
    defaultValue: "2024-10-21",
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
  {
    key: "FEATURE_FLAGS_JSON",
    description: "Feature flags as JSON object.",
    kind: "json",
    defaultValue: {},
    meta: { hotReload: true, sensitive: false, restartRequired: false },
  },
] as const satisfies readonly ConfigDefinition[];

export type DefaultConfigDefinition = (typeof DEFAULT_CONFIG_DEFINITIONS)[number];
export type DefaultConfigKey = DefaultConfigDefinition["key"];
