export {
  classifyMatchConfidence,
  computeTokenOverlap,
  DEFAULT_SHARED_MATCH_POLICY,
  normalizeMatchText,
  rankCandidatesShared,
  resolveSharedMatchPolicy,
  scoreCandidateCanonical,
  tokenizeMatchText,
  type RankCandidatesOptions,
  type SharedMatchConfidence,
  type SharedMatchCandidate,
  type SharedMatchDecision,
  type SharedMatchPath,
  type SharedMatchPolicy,
  type SharedRankedCandidate,
  type SharedScoreBreakdown,
} from "./shared-core";
